description: llm4em

environment:
  image: docker.cipsup.cn/wangtianshu/base
  force_pull_image: true

bind_mounts:
  - host_path: /shared_home/tianshu2020
    container_path: /home/tianshu2020
  - host_path: /shared_home/tianshu2020/linuxbrew
    container_path: /home/linuxbrew/.linuxbrew
  # - host_path: /ceph_home/tianshu2020
  #   container_path: /home/tianshu2020
  # - host_path: /ceph_home/tianshu2020/linuxbrew
  #   container_path: /home/linuxbrew/.linuxbrew
  - host_path: /ceph_home
    container_path: /ceph_home
  - host_path: /shared_home
    container_path: /shared_home

resources:
  slots: 2
  resource_pool: A100-40G
  shm_size: 32G

work_dir: /home/tianshu2020
